'use client'
import { useState } from 'react'
import { Download, RefreshCw, Copy, Check, ChevronDown, ChevronRight } from 'lucide-react'
import type { PerfOutput, PerfInput } from '@/lib/types'

interface Props { output: PerfOutput; input: PerfInput; onReset: () => void }

const PRIORITY_STYLE = {
  critical: { bg: 'rgba(239,68,68,0.12)', text: '#FCA5A5', label: '🔴 Critical' },
  high:     { bg: 'rgba(249,115,22,0.12)', text: '#FDBA74', label: '🟠 High' },
  medium:   { bg: 'rgba(245,158,11,0.12)', text: '#FCD34D', label: '🟡 Medium' },
  low:      { bg: 'rgba(16,185,129,0.12)',  text: '#6EE7B7', label: '🟢 Low' },
}

const SCENARIO_COLOR: Record<string, string> = {
  smoke: '#10B981', load: '#3B82F6', stress: '#F97316', soak: '#8B5CF6', spike: '#EF4444', breakpoint: '#F59E0B',
}

function Section({ title, children, defaultOpen = true }: { title: string; children: React.ReactNode; defaultOpen?: boolean }) {
  const [open, setOpen] = useState(defaultOpen)
  return (
    <div className="rounded-2xl overflow-hidden" style={{ background: 'var(--bg-card)', border: '1px solid var(--border-default)' }}>
      <button className="w-full flex items-center justify-between px-5 py-3 border-b" style={{ borderColor: open ? 'var(--border-default)' : 'transparent', background: 'var(--bg-elevated)' }} onClick={() => setOpen(o => !o)}>
        <h3 className="font-bold text-sm" style={{ color: 'var(--text-primary)' }}>{title}</h3>
        {open ? <ChevronDown size={14} style={{ color: 'var(--text-dimmer)' }} /> : <ChevronRight size={14} style={{ color: 'var(--text-dimmer)' }} />}
      </button>
      {open && <div className="p-5">{children}</div>}
    </div>
  )
}

function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = useState(false)
  function copy() { navigator.clipboard.writeText(text); setCopied(true); setTimeout(() => setCopied(false), 2000) }
  return (
    <button onClick={copy} className="flex items-center gap-1.5 text-xs px-3 py-1.5 rounded-lg font-medium" style={{ background: 'var(--bg-elevated)', color: 'var(--text-secondary)', border: '1px solid var(--border-default)' }}>
      {copied ? <><Check size={12} /> Copied!</> : <><Copy size={12} /> Copy</>}
    </button>
  )
}

function exportAll(o: PerfOutput, i: PerfInput): string {
  return [
    `# Performance Test Plan: ${i.appName}`,
    `**Peak VUs:** ${i.peakConcurrent} · **p95 SLA:** ${i.slaP95}ms · **p99 SLA:** ${i.slaP99}ms · **Max error rate:** ${i.slaErrorRate}%`,
    ``, `## Strategy`, o.strategy,
    ``, `## Test Execution Order`, o.testOrder.map((t, i) => `${i + 1}. ${t}`).join('\n'),
    ``, `## Load Scenarios`,
    ...o.scenarios.flatMap(s => [
      `### ${s.name} (${s.type})`, s.description,
      `**Stages:**`, ...s.stages.map(st => `- ${st.duration} → ${st.target} VUs (${st.description})`), `**Rationale:** ${s.rationale}`, ``
    ]),
    `## Endpoint Coverage`,
    `| Endpoint | Method | Priority | Load Share |`,
    `|----------|--------|----------|------------|`,
    ...o.endpoints.map(e => `| ${e.endpoint} | ${e.method} | ${e.priority} | ${e.loadShare} |`),
    ``, `## k6 Script`, '```javascript', o.k6Script, '```',
    ``, `## JMeter Plan`, o.jmeterSummary,
    ``, `## SLA Thresholds`,
    `| Metric | Threshold | Alert |`,
    `|--------|-----------|-------|`,
    ...o.thresholds.map(t => `| ${t.metric} | ${t.threshold} | ${t.alertRecommendation} |`),
    ``, `## Monitoring Checklist`, ...o.monitoringChecklist.map(m => `- [ ] ${m}`),
    ``, `## Risks`, ...o.risks.map(r => `- ⚠ ${r}`),
    ``, `## Recommendations`, ...o.recommendations.map(r => `- ${r}`),
    ``, `---`, `*Generated by Perf Test Planner AI — validate scripts in staging before production*`,
  ].join('\n')
}

export default function PerfReport({ output, input, onReset }: Props) {
  function handleExportMd() {
    const blob = new Blob([exportAll(output, input)], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob); const a = document.createElement('a')
    a.href = url; a.download = `perf-plan-${input.appName.toLowerCase().replace(/\s+/g, '-')}.md`; a.click(); URL.revokeObjectURL(url)
  }
  function handleExportK6() {
    const blob = new Blob([output.k6Script], { type: 'text/javascript' })
    const url = URL.createObjectURL(blob); const a = document.createElement('a')
    a.href = url; a.download = `k6-${input.appName.toLowerCase().replace(/\s+/g, '-')}.js`; a.click(); URL.revokeObjectURL(url)
  }

  return (
    <div className="space-y-4">
      {/* Header */}
      <div className="rounded-2xl p-5 flex items-start justify-between gap-4 flex-wrap" style={{ background: 'var(--bg-card)', border: '1px solid var(--border-default)' }}>
        <div>
          <h1 className="text-xl font-black mb-1" style={{ color: 'var(--text-primary)' }}>⚡ {input.appName} — Performance Test Plan</h1>
          <div className="flex items-center gap-3 flex-wrap text-xs" style={{ color: 'var(--text-secondary)' }}>
            <span>👥 Peak {input.peakConcurrent} VUs</span>
            <span>⏱ p95 &lt; {input.slaP95}ms</span>
            <span>⏱ p99 &lt; {input.slaP99}ms</span>
            <span>❌ Error &lt; {input.slaErrorRate}%</span>
            <span>📋 {output.scenarios.length} scenarios</span>
          </div>
        </div>
        <div className="flex gap-2 flex-wrap">
          <button onClick={handleExportK6} className="flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-semibold text-white" style={{ background: 'rgba(249,115,22,0.85)' }}>
            <Download size={14} /> k6 Script .js
          </button>
          <button onClick={handleExportMd} className="flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-semibold" style={{ background: 'var(--bg-elevated)', color: 'var(--text-secondary)', border: '1px solid var(--border-default)' }}>
            <Download size={14} /> Full Plan .md
          </button>
          <button onClick={onReset} className="flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-semibold text-white" style={{ background: 'var(--accent-grad)' }}>
            <RefreshCw size={14} /> New Plan
          </button>
        </div>
      </div>

      {/* Strategy */}
      <Section title="🎯 Test Strategy">
        <p className="text-sm leading-relaxed" style={{ color: 'var(--text-secondary)' }}>{output.strategy}</p>
        {output.testOrder.length > 0 && (
          <div className="mt-3 flex items-center gap-2 flex-wrap">
            <span className="text-xs font-bold" style={{ color: 'var(--text-dimmer)' }}>Execution order:</span>
            {output.testOrder.map((t, i) => (
              <span key={i} className="flex items-center gap-1.5">
                <span className="text-xs font-bold px-2.5 py-1 rounded-full" style={{ background: `${SCENARIO_COLOR[t.toLowerCase()] ?? '#64748B'}22`, color: SCENARIO_COLOR[t.toLowerCase()] ?? '#94A3B8' }}>{t}</span>
                {i < output.testOrder.length - 1 && <span style={{ color: 'var(--text-dimmer)' }}>→</span>}
              </span>
            ))}
          </div>
        )}
      </Section>

      {/* Scenarios */}
      <Section title="📊 Load Scenarios">
        <div className="space-y-4">
          {output.scenarios.map((s, i) => {
            const color = SCENARIO_COLOR[s.type] ?? '#94A3B8'
            return (
              <div key={i} className="rounded-xl p-4" style={{ background: 'var(--bg-elevated)', border: `1px solid ${color}33` }}>
                <div className="flex items-center gap-2 mb-2">
                  <span className="text-xs font-bold px-2.5 py-1 rounded-full" style={{ background: `${color}22`, color }}>{s.type.toUpperCase()}</span>
                  <span className="font-bold text-sm" style={{ color: 'var(--text-primary)' }}>{s.name}</span>
                  <span className="text-xs ml-auto" style={{ color: 'var(--text-dimmer)' }}>Peak: {s.vus} VUs</span>
                </div>
                <p className="text-xs mb-3" style={{ color: 'var(--text-secondary)' }}>{s.description}</p>
                {/* Stage visualisation */}
                <div className="flex items-end gap-1 h-10 mb-2">
                  {s.stages.map((st, j) => {
                    const maxTarget = Math.max(...s.stages.map(x => x.target), 1)
                    const heightPct = Math.max((st.target / maxTarget) * 100, 4)
                    return (
                      <div key={j} className="flex-1 flex flex-col items-center gap-0.5" title={`${st.duration}: ${st.target} VUs`}>
                        <div className="w-full rounded-t-sm" style={{ height: `${heightPct}%`, background: color, opacity: 0.7 }} />
                      </div>
                    )
                  })}
                </div>
                <div className="flex gap-3 flex-wrap">
                  {s.stages.map((st, j) => (
                    <span key={j} className="text-[10px]" style={{ color: 'var(--text-dimmer)' }}>{st.duration} → <strong style={{ color }}>{st.target} VUs</strong></span>
                  ))}
                </div>
                <p className="text-[11px] mt-2 italic" style={{ color: 'var(--text-dimmer)' }}>💡 {s.rationale}</p>
              </div>
            )
          })}
        </div>
      </Section>

      {/* Endpoints */}
      <Section title="🔗 Endpoint Coverage">
        <div className="space-y-2">
          {output.endpoints.map((e, i) => {
            const p = PRIORITY_STYLE[e.priority]
            return (
              <div key={i} className="p-4 rounded-xl" style={{ background: 'var(--bg-elevated)', border: '1px solid var(--border-default)' }}>
                <div className="flex items-center gap-2 flex-wrap mb-1.5">
                  <span className="text-xs font-bold px-1.5 py-0.5 rounded font-mono" style={{ background: 'rgba(59,130,246,0.12)', color: '#60A5FA' }}>{e.method}</span>
                  <code className="text-xs font-mono" style={{ color: 'var(--text-primary)' }}>{e.endpoint}</code>
                  <span className="text-[10px] font-bold px-2 py-0.5 rounded-full ml-auto" style={{ background: p.bg, color: p.text }}>{p.label}</span>
                  <span className="text-xs" style={{ color: 'var(--text-dimmer)' }}>{e.loadShare}</span>
                </div>
                <div className="flex flex-wrap gap-1.5 mb-1">
                  {e.checks.map((c, j) => <span key={j} className="text-[10px] px-2 py-0.5 rounded" style={{ background: 'rgba(16,185,129,0.08)', color: '#34D399' }}>✓ {c}</span>)}
                </div>
                {e.notes && <p className="text-[11px] italic" style={{ color: 'var(--text-dimmer)' }}>{e.notes}</p>}
              </div>
            )
          })}
        </div>
      </Section>

      {/* k6 Script */}
      <Section title="📝 k6 Script (Runnable)">
        <div className="flex justify-end mb-2 gap-2">
          <CopyButton text={output.k6Script} />
          <button onClick={handleExportK6} className="flex items-center gap-1.5 text-xs px-3 py-1.5 rounded-lg font-medium text-white" style={{ background: 'rgba(249,115,22,0.8)' }}>
            <Download size={12} /> Download .js
          </button>
        </div>
        <pre className="code-block">{output.k6Script}</pre>
      </Section>

      {/* JMeter */}
      <Section title="☕ JMeter Plan Summary" defaultOpen={false}>
        <p className="text-sm leading-relaxed whitespace-pre-wrap" style={{ color: 'var(--text-secondary)' }}>{output.jmeterSummary}</p>
      </Section>

      {/* Thresholds */}
      <Section title="📏 SLA Thresholds & Alerts">
        <div className="space-y-2">
          {output.thresholds.map((t, i) => (
            <div key={i} className="p-3 rounded-xl grid grid-cols-1 sm:grid-cols-3 gap-2" style={{ background: 'var(--bg-elevated)', border: '1px solid var(--border-default)' }}>
              <code className="text-xs font-mono" style={{ color: '#FDBA74' }}>{t.metric}</code>
              <code className="text-xs font-mono font-bold" style={{ color: '#34D399' }}>{t.threshold}</code>
              <p className="text-xs" style={{ color: 'var(--text-dimmer)' }}>🔔 {t.alertRecommendation}</p>
            </div>
          ))}
        </div>
      </Section>

      {/* Monitoring + Risks + Recs */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <Section title="📡 Monitoring Checklist">
          <ul className="space-y-1.5">
            {output.monitoringChecklist.map((m, i) => (
              <li key={i} className="flex items-start gap-2 text-xs" style={{ color: 'var(--text-secondary)' }}>
                <span className="mt-0.5 shrink-0" style={{ color: 'var(--accent-green)' }}>□</span>{m}
              </li>
            ))}
          </ul>
        </Section>
        <Section title="⚠️ Risks">
          <ul className="space-y-1.5">
            {output.risks.map((r, i) => (
              <li key={i} className="flex items-start gap-2 text-xs" style={{ color: 'var(--text-secondary)' }}>
                <span className="shrink-0" style={{ color: 'var(--accent-amber)' }}>⚠</span>{r}
              </li>
            ))}
          </ul>
        </Section>
        <Section title="💡 Recommendations">
          <ul className="space-y-1.5">
            {output.recommendations.map((r, i) => (
              <li key={i} className="flex items-start gap-2 text-xs" style={{ color: 'var(--text-secondary)' }}>
                <span className="shrink-0" style={{ color: 'var(--accent-orange)' }}>→</span>{r}
              </li>
            ))}
          </ul>
        </Section>
      </div>
    </div>
  )
}
